### ISSUE TITLE
Doesn't handle CSV

### ISSUE THREAD

**Issue by lhannest** [NCATS-Tangerine/HMDB-knowledge-beacon#8]
https://translator.ncats.io/hmdb-knowledge-beacon/exactmatches?c=kegg.pathway:hsa04940,kegg.pathway:hsa04950,kegg.pathway:hsa04930,NDEX:c53894ce-8e47-11e5-b435-06603eb7f303_87987048,NDEX:c53894ce-8e47-11e5-b435-06603eb7f303_87987140,ncbigene:16847,ncbigene:832208,NDEX:f0dd2c31-b2ed-11e8-9520-0ac135e8bacf_3651,NDEX:f0dd2c31-b2ed-11e8-9520-0ac135e8bacf_13369,SDIS:Diabetes

It returns this:

```json
[
   {
      "id":"kegg.pathway:hsa04940,kegg.pathway:hsa04950,kegg.pathway:hsa04930,NDEX:c53894ce-8e47-11e5-b435-06603eb7f303_87987048,NDEX:c53894ce-8e47-11e5-b435-06603eb7f303_87987140,ncbigene:16847,ncbigene:832208,NDEX:f0dd2c31-b2ed-11e8-9520-0ac135e8bacf_3651,NDEX:f0dd2c31-b2ed-11e8-9520-0ac135e8bacf_13369,SDIS:Diabetes",
      "within_domain":false,
      "has_exact_matches":[]
   }
]
```

Arrays are supposed to be encoded in the multi format (`?c=A&c=B&c=C`) rather than csv format (`?c=A,B,C`), so this behavior is not incorrect. But it would be ideal for both to be supported, if it wouldn't be much trouble. If it would be difficult to support, then disregard.

**Comment by vdancik** [comment]
Unfortunately allowing csv format for arrays in general will not work since chemical names routinely contain commas and thus would be incorrectly interpreted as arrays.

**Comment by lhannest** [comment]
I didn't know that, I'll close this issue then.
